package com.r_mobile;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.r_mobile.Category;
import com.r_mobile.Phrase;
import com.r_mobile.Translate;

import com.r_mobile.CategoryDao;
import com.r_mobile.PhraseDao;
import com.r_mobile.TranslateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig phraseDaoConfig;
    private final DaoConfig translateDaoConfig;

    private final CategoryDao categoryDao;
    private final PhraseDao phraseDao;
    private final TranslateDao translateDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        phraseDaoConfig = daoConfigMap.get(PhraseDao.class).clone();
        phraseDaoConfig.initIdentityScope(type);

        translateDaoConfig = daoConfigMap.get(TranslateDao.class).clone();
        translateDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        phraseDao = new PhraseDao(phraseDaoConfig, this);
        translateDao = new TranslateDao(translateDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Phrase.class, phraseDao);
        registerDao(Translate.class, translateDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        phraseDaoConfig.getIdentityScope().clear();
        translateDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public PhraseDao getPhraseDao() {
        return phraseDao;
    }

    public TranslateDao getTranslateDao() {
        return translateDao;
    }

}
